"""initial migration

Revision ID: 73e5da42a059
Revises: 
Create Date: 2025-03-07 21:29:00.061906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e5da42a059'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('expenses',
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('expense_amount', sa.Float(), nullable=False),
    sa.Column('expense_description', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('fk_expense_category', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fk_expense_category'], ['categories.category_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expense_id'),
    sa.UniqueConstraint('expense_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    op.drop_table('categories')
    # ### end Alembic commands ###
